services:
  backend:
    build: .  
    container_name: task_backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tasktracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2008
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
    depends_on:
      - postgres
      
  postgres:
    image: postgres:16-alpine
    container_name: task_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2008
      - POSTGRES_DB=tasktracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: task_mail
    ports:
      - "8025:8025" # Интерфейс почты
      - "1025:1025" # SMTP-сервер

volumes:
  pgdata: