spring.application.name=tasktracker

# Настройки БД
spring.datasource.url=jdbc:postgresql://localhost:5434/tasktracker
spring.datasource.username=postgres
spring.datasource.password=2008
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase (миграции)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
server.port=9090

# JWT Секретный ключ
jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
jwt.expiration=86400000

# Почта (Mailpit в Docker)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false